#!/bin/bash
# Generated by Claude Flow Designer — headless runner.
set -euo pipefail

claude -p 'Run the test suite. For each failing test, diagnose and fix the code, then re-run until green. Do not weaken assertions.' --model 'sonnet' --output-format stream-json --max-turns 40 --verbose
