// Generated by claude-flow-designer. Do not edit by hand.
export const meta = { name: "test-fix", description: "Run tests and fix failures until green" }

let round = 0
let lastProgress = null
let fixLoop
while (round < 2) {
  const check = await agent(`Run the test suite and report whether it passed.`, { schema: {
  "properties": {
    "passed": {
      "type": "boolean"
    },
    "progress": {
      "type": "number"
    }
  },
  "type": "object"
}, label: `check` })
  fixLoop = check
  if (check.passed) break
  if (round > 0 && check.progress !== undefined && check.progress === lastProgress) break
  lastProgress = check.progress
  await agent(`Fix the failures reported: ${JSON.stringify(check)}.`, { label: `fix` })
  round++
}

return fixLoop
