// Generated by claude-flow-designer. Do not edit by hand.
export const meta = { name: "draft-angles", description: "Draft a plan from several angles concurrently, then merge" }

const draftAngles = await parallel([
  () => agent(`Draft the plan optimizing for speed.`, { label: `speed` }),
  () => agent(`Draft the plan optimizing for safety.`, { label: `safety` }),
  () => agent(`Draft the plan optimizing for cost.`, { label: `cost` }),
])

const merge = await agent(`Weigh the drafts in ${JSON.stringify(draftAngles)} and pick the best synthesis.`, { label: `merge` })

return merge
