// Generated by claude-flow-designer. Do not edit by hand.
export const meta = { name: "summarize", description: "Summarize the input in three bullets" }

const summarize = await agent(`Summarize the following in three bullets:
${JSON.stringify(args)}`, { label: `summarize` })

return summarize
