// Generated by claude-flow-designer. Do not edit by hand.
export const meta = { name: "grade-prs", description: "Grade each PR number passed in args" }

const gradePR = await pipeline(args, item => agent(`Grade PR #${item} for review quality (0-10) with a one-line reason.`, { label: `PR ${item}` }))

return gradePR
