// Generated by claude-flow-designer. Do not edit by hand.
export const meta = { name: "review-dims", description: "Review each dimension concurrently, then merge" }

const listDimensions = await agent(`List the review dimensions.`, { schema: {
  "properties": {
    "dims": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "dims"
  ],
  "type": "object"
} })

const reviewEach = await parallel(listDimensions.dims.map(d => () => agent(`Review dimension ${d} of ${JSON.stringify(listDimensions)}.`, { label: `review:${d}`, phase: 'Review' })))

return reviewEach.filter(Boolean)
