// Generated hook .sh scripts. Conventions (SPEC-CODEGEN "Generated script
// conventions"): #!/bin/bash, set -euo pipefail, jq guard first, read stdin once,
// decision tail per the blockability table. Output MUST pass shellcheck.
import { BLOCKABLE_EVENTS } from '../schema/types.js';
import type { HookEvent } from '../schema/types.js';
import type { DecisionData } from '../schema/nodes.js';

const GUARD = 'command -v jq >/dev/null || { echo "jq required" >&2; exit 1; }';

/** hookSpecificOutput.permissionDecision value for a PreToolUse-style decision. */
function permissionDecision(mode: DecisionData['mode']): string | undefined {
  switch (mode) {
    case 'allow':
      return 'allow';
    case 'deny':
      return 'deny';
    case 'ask':
      return 'ask';
    default:
      return undefined;
  }
}

/**
 * Build the JSON object a decision emits (universal + event-specific fields),
 * as a jq object literal string. Returns null when the decision is a bare
 * exit-2 block (no JSON body).
 */
function decisionJsonArgs(event: HookEvent, dec: DecisionData): { args: string[]; obj: string } {
  // args are emitted as: --arg <field> '<quoted-value>' — only the value is quoted.
  const args: string[] = [];
  const parts: string[] = [];
  const addStr = (key: string, jqField: string, value: string) => {
    args.push(`--arg ${jqField} ${shSingleQuote(value)}`);
    parts.push(`${key}: $${jqField}`);
  };

  if (event === 'PreToolUse' || event === 'PermissionRequest') {
    const pd = permissionDecision(dec.mode);
    const inner: string[] = [`hookEventName: "${event}"`];
    if (pd) inner.push(`permissionDecision: "${pd}"`);
    if (dec.reason) addStr('permissionDecisionReason', 'reason', dec.reason);
    // reason lives inside hookSpecificOutput for PreToolUse
    const hso = dec.reason
      ? `{ ${inner.join(', ')}, permissionDecisionReason: $reason }`
      : `{ ${inner.join(', ')} }`;
    parts.push(`hookSpecificOutput: ${hso}`);
  } else if (dec.mode === 'block') {
    parts.push('decision: "block"');
    if (dec.reason) addStr('reason', 'reason', dec.reason);
  } else if (dec.mode === 'stopAll') {
    parts.push('continue: false');
    if (dec.reason) addStr('stopReason', 'reason', dec.reason);
  }

  if (dec.additionalContext) addStr('additionalContext', 'actx', dec.additionalContext);
  if (dec.systemMessage) addStr('systemMessage', 'sysmsg', dec.systemMessage);
  if (dec.suppressOutput) parts.push('suppressOutput: true');

  return { args, obj: `{ ${parts.join(', ')} }` };
}

export interface ScriptSpec {
  event: HookEvent;
  /** Inline body from hook.command.scriptBody, or a single command line. */
  body?: string;
  /** The decision this hook emits, if any. */
  decision?: DecisionData;
}

/**
 * Emit a complete, shellcheck-clean hook script. The jq guard + stdin read are
 * always present (CF115 invariant); `input` gets a documented SC2034 suppression
 * when nothing downstream references it.
 */
export function emitHookScript(spec: ScriptSpec): string {
  const { event, body, decision } = spec;
  const lines: string[] = [];
  const post: string[] = []; // everything after the input read

  if (body && body.trim()) post.push(body.trimEnd());

  const referencesInput = /\binput\b/.test(body ?? '');

  if (decision) {
    const blockable = BLOCKABLE_EVENTS.has(event);
    const wantsExit2 =
      decision.blockStyle === 'exit2' &&
      (decision.mode === 'block' || decision.mode === 'deny') &&
      blockable;
    if (wantsExit2) {
      // Bare exit-2 block: reason to stderr, exit 2.
      if (decision.reason) {
        post.push(`echo ${shSingleQuote(decision.reason)} >&2`);
      }
      post.push('exit 2');
    } else {
      const { args, obj } = decisionJsonArgs(event, decision);
      const argStr = args.length ? args.join(' ') + ' ' : '';
      post.push(`jq -n ${argStr}${shSingleQuote(obj)}`);
      post.push('exit 0');
    }
  }

  // Header
  lines.push('#!/bin/bash');
  lines.push(`# Generated by Claude Flow Designer — hook for ${event}. Do not edit by hand.`);
  lines.push('set -euo pipefail');
  lines.push(GUARD);
  lines.push('');
  if (!referencesInput) {
    lines.push('# stdin carries the hook payload; read it even if this handler ignores fields.');
    lines.push('# shellcheck disable=SC2034');
  }
  lines.push('input=$(cat)');
  if (post.length) {
    lines.push('');
    lines.push(...post);
  }
  return lines.join('\n') + '\n';
}

/** Single-quote a string for POSIX sh, escaping embedded single quotes. */
export function shSingleQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}
