// Generated by claude-flow-designer. Do not edit by hand.
export const meta = { name: "branch-review", description: "Review a change and act on the verdict" }

const review = await agent(`Review the current diff. Report whether it is safe to merge.`, { schema: {
  "properties": {
    "safe": {
      "type": "boolean"
    }
  },
  "type": "object"
}, label: `review` })

if (review.safe) {
  const approve = await agent(`Draft an approving PR comment.`, { label: `approve` })
} else {
  const requestChanges = await agent(`Draft a request-changes PR comment citing ${JSON.stringify(review)}.`, { label: `request` })
}

return review
