#!/bin/bash
# Generated by Claude Flow Designer — hook for SessionStart. Do not edit by hand.
set -euo pipefail
command -v jq >/dev/null || { echo "jq required" >&2; exit 1; }

# stdin carries the hook payload; read it even if this handler ignores fields.
# shellcheck disable=SC2034
input=$(cat)

ctx=$(git -C "$CLAUDE_PROJECT_DIR" status --short 2>/dev/null || echo "no git")
printf '%s' "$ctx" > /tmp/clauflow-ctx.txt
jq -n --arg actx 'Repo status loaded at session start.' '{ hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: $actx } }'
exit 0
