#!/bin/bash
# Generated by Claude Flow Designer — hook for PreToolUse. Do not edit by hand.
set -euo pipefail
command -v jq >/dev/null || { echo "jq required" >&2; exit 1; }

input=$(cat)

cmd=$(jq -r '.tool_input.command // ""' <<<"$input")
if printf '%s' "$cmd" | grep -Eq 'rm[[:space:]]+-rf|:\(\)\{'; then
  blocked=1
else
  blocked=0
fi
if [ "$blocked" -eq 0 ]; then exit 0; fi
jq -n --arg reason 'Destructive command blocked by the security gate.' '{ hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: $reason } }'
exit 0
