// Generated by claude-flow-designer. Do not edit by hand.
export const meta = { name: "audit-routes", description: "Audit route handlers for missing auth" }

const listRoutes = await agent(`List every .ts file under src/routes/.`, { schema: {
  "properties": {
    "files": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "files"
  ],
  "type": "object"
} })

const auditRoutes = await pipeline(listRoutes.files, item => agent(`Audit ${item} for missing authentication checks.`, { label: `${item}` }))

return auditRoutes.filter(Boolean)
