// Generated by claude-flow-designer. Do not edit by hand.
export const meta = { name: "poc-phases", description: "A phased build with a verify branch" }

phase("Understand")
const spec = await agent(`Write a spec for ${JSON.stringify(args)}.`, { label: `spec` })

phase("Verify")
const check = await agent(`Verify ${JSON.stringify(spec)}.`, { schema: {
  "properties": {
    "failing": {
      "type": "boolean"
    }
  },
  "type": "object"
}, label: `check` })

if (check.failing) {
  const repair = await agent(`Repair the failures in ${JSON.stringify(check)}.`, { label: `repair` })
}

return check
